adoptions/urls.py
from django.urls import path
from . import views

app_name = 'adoptions'

urlpatterns = [
    path('animal/<int:id>', views.animal, name='animal'),
    path('toggle_favorite/<int:animal_id>/', views.toggle_favorite, name='toggle_favorite'),
    path('todos/', views.todos, name='todos'),
]

app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.home, name='home'),
    path('meus_dados/', views.meus_dados, name='meus_dados'),
    path('favoritos/', views.favoritos, name='favoritos'),
    path('meus_animais/', views.meus_animais, name='meus_animais'),
    path('excluir_conta/', views.excluir_conta, name='excluir_conta'),
    path('sair/', views.sair_tela, name='sair_tela'),
]

ourAnimal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('usuario/', include('user.urls')),
    path('animais/', include('adoptions.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/components/minha_conta/animal.html
{% load static %}
<a class="animal-click" href="{% url "adoptions:animal" animal.id %}">
    <div class="card_animal">
        <div class="imagem_animal">
            {% if animal.images.exists %}
                {% for image in animal.images.all %}
                    {% if forloop.counter0 <= 0 %} 
                    <img class='image_animal' src="{{ image.image.url }}" alt="Imagem do {{ animal.nome }}">  
                        {% endif %}
                {% endfor %}
            {% else %}
                <img src="{% static 'images/animals/sem_foto.jpg' %}" alt="O animal {{ animal.nome }} está sem foto" style="max-height: 200px;">
            {% endif %}
        </div>
        <div class="informacoes_animal">
            <div class="texto_animal">
                <p class="card-text">Animal: <b>{{ animal.tipo }}</b></p>
                <p class="card-text">Raça: <b>{{ animal.raca }}</b></p>
                <p class="card-text">Idade: <b>{{ animal.idade }} meses</b></p>
                <p class="card-text">Estado: <b>{{ animal.user.estado }}</b></p>
            </div>
            <div class="genero_animal">
                {% if animal.genero == 'Macho' %}
                    <img class='gender-male' src=" {% static "images/icons/male.png" %} " alt="male">
                {% elif animal.genero == 'Femêa' %}
                    <img class='gender-female' src=" {% static "images/icons/female.png" %} " alt="female" style="width: 80px; padding-right: 0px;">
                {% endif %}
            </div>
        </div>
    </div>
</a>

app/templates/components/minha_conta/base.html
{% extends "base/base.html" %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static "app/minha_conta.css" %}">
    <link rel="stylesheet" href="{% static "gComponents/animalCard.css" %}">
{% endblock style %}

{% block content %}
    <div class="total">
        <div class="box">
            <div class="barra-lateral" id="sidebar">
                <h4>Minha conta</h4>
                <ul>
                    <a href="{% url 'app:meus_dados' %}">
                        <div class="nav-conta {% if request.resolver_match.url_name == 'meus_dados' %}active{% endif %}">
                            <li>Meus Dados</li>
                        </div>
                    </a>
                    <a href="{% url 'app:meus_animais' %}">
                        <div class="nav-conta {% if request.resolver_match.url_name == 'meus_animais' %}active{% endif %}">
                            <li>Meus Animais</li>
                        </div>
                    </a>
                    <a href="{% url 'app:favoritos' %}">
                        <div class="nav-conta {% if request.resolver_match.url_name == 'favoritos' %}active{% endif %}">
                            <li>Favoritos</li>
                        </div>
                    </a>
                    <a href="{% url 'app:sair_tela' %}">
                        <div class="nav-conta {% if request.resolver_match.url_name == 'sair_tela' %}active{% endif %}">
                            <li>Sair da Conta</li>
                        </div>
                    </a>
                    <a href="{% url 'app:excluir_conta' %}">
                        <div class="nav-conta {% if request.resolver_match.url_name == 'excluir_conta' %}active{% endif %}">
                            <li>Deletar Conta</li>
                        </div>
                    </a>
                    <a onclick="window.history.back()" class="voltar">
                        <div class="nav-conta">
                            <li>← página anterior </li> 
                        </div>
                    </a>
                </ul>
            </div>
            <div class="informacoes">
                <div class="title">
                    <h1 class="title-text">{% block title %}{% endblock title %}</h1>
                </div>
                {% block pre_conteudo %}
                {% endblock pre_conteudo %}
                <div class="conteudo">
                    {% if messages %}
                        <div class="messages">
                            {% for message in messages %}
                                <div class="alert {{ message.tags }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% block conteudo %}
                    {% endblock conteudo %}
                </div>
                {% block conteudo_dois %}{% endblock conteudo_dois %}
            </div>
        </div>
    </div>
{% endblock content %}